service: dynamo

provider:
  name: aws
  stage: prod
  region: ap-northeast-1
  environment: ${file(conf/${self:provider.stage}.yml)}
  # environment: ${file(src/conf/${self:provider.stage}.yml)}　何故かこう書いててもデプロイできた

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
