# https://taskfile.dev

version: "3"

env:
  # MIGRATION_ROOT: "tools/migrations"
  # SEED_ROOT: "tools/seeder"
  LOCALSTACK_HOST: http://localstack

tasks:
  local-dynamodb-deploy:
    desc: "LocalStackにDynamoDBをデプロイ"
    cmds:
      - cd dynamodb && serverless deploy --stage dev --force --config serverless.yml
      - task create-user

  local-dynamodb-destroy:
    desc: "LocalStackのDynamoDBを削除"
    cmds:
      - cd dynamodb && serverless remove --stage dev --config serverless.yml

  production-deploy-aws:
    desc: "Python版を本番AWSにデプロイ"
    desc: "本番AWSにデプロイ"
    cmds:
      - serverless deploy --stage prod --force
      - serverless deploy --stage prod --config serverless.prod.yml

  production-destroy-aws:
    desc: "本番AWSリソースを削除"
    cmds:
      - serverless remove --stage prod --config serverless.prod.yml

  show-user-table:
    desc: "show-user-table"
    cmds:
      - aws dynamodb scan --table-name Users --endpoint-url http://localstack:4566 --no-paginate --no-cli-pager

  create-user:
    desc: "create user table"
    cmds:
      - aws dynamodb put-item --table-name Users --item '{"id":{"S":"1"},"name":{"S":"Alice"},"email":{"S":"alice@example.com"}}' --endpoint-url http://localstack:4566 --no-paginate --no-cli-pager
      - aws dynamodb put-item --table-name Users --item '{"id":{"S":"2"},"name":{"S":"Bob"},"email":{"S":"bob@example.com"}}' --endpoint-url http://localstack:4566 --no-paginate --no-cli-pager
      - aws dynamodb put-item --table-name Users --item '{"id":{"S":"3"},"name":{"S":"Charlie"},"email":{"S":"charlie@example.com"}}' --endpoint-url http://localstack:4566 --no-paginate --no-cli-pager
