service: lambda-demo-python

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-northeast-1

plugins:
  # - serverless-offline
  - serverless-localstack
  - serverless-python-requirements

custom:
  localstack:
    stages:
      - dev
    host: http://localstack
    edgePort: 4566
    apiGateway:
      restApiId: hqbfcj2rmp

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  users:
    handler: handler.get_users
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: users
          method: get
          cors: true

  user:
    handler: handler.get_user0
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: users/{id}
          method: get
          cors: true

package:
  include:
    - handler.py
