# https://taskfile.dev

version: "3"

env:
  # MIGRATION_ROOT: "tools/migrations"
  # SEED_ROOT: "tools/seeder"

tasks:
  setup:
    desc: "ローカル環境のセットアップを行う。(gitコマンドが使用できるようにする)"
    cmds:
      - cp {{.APP_ROOT}}/.gitconfig /root/.gitconfig
      - git config --global core.autocrlf input
      - git config --global --add safe.directory {{.APP_ROOT}}
      - cd lambda && npm install # ローカルで開発する際このディレクトリの依存関係のインストールで充足するので、このディレクトリでインストールする。
      - cd lambda && serverless plugin install -n serverless-python-requirements
      - cd lambda && serverless plugin install -n serverless-localstack
      - cd lambda && pip install -r requirements.txt
      - task aws-configure-setup
      # - chmod +x {{.APP_ROOT}}/.github/hooks/pre-commit
      # - git config core.hooksPath {{.APP_ROOT}}/.github/hooks
      # わざわざコピーする理由は、commit時に毎回メアドとユーザー名の設定(.gitconfigの作成)を求められ面倒なので、git cloneするなら作成済みであろう.gitconfigを使うという魂胆である。
      # だが、Windowsユーザーが.gitconfigを使用中と解釈されるようでgit configコマンドが失敗するため、ファイルをコピーする必要がある。
      # core.autocrlf inputを使用する理由は、Linuxの改行コードが原因で差分が表示されてしまうため。
      # safe.directory $APP_ROOTを使用する理由は、WSL2側に配置しgitを使うには毎回求められるため。

  aws-configure-setup:
    desc: "aws configure setup"
    cmds:
      - aws configure set aws_access_key_id {$AWS_ACCESS_KEY_ID}
      - aws configure set aws_secret_access_key {$AWS_SECRET_ACCESS_KEY}
      - aws configure set default.region {$AWS_REGION}
      - aws configure set default.output json
      - aws configure list
