version: "3"
services:
  python:
    build:
      context: ../
      dockerfile: .devcontainer/infra/python/Dockerfile
    env_file:
      - .env
    tty: true
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../:/data
      - ~/.gitconfig:/data/.gitconfig

  localstack:
    image: localstack/localstack:4.6
    ports:
      - ${LOCALSTACK_PORT}:4566
    environment:
      - SERVICES=lambda,apigateway,dynamodb,cloudformation,s3,iam,sts,logs
      - DEBUG=1
      - LAMBDA_DOCKER_FLAGS=-e DOCKER_LAMBDA_STAY_OPEN=1
      - LAMBDA_REMOVE_CONTAINERS=false
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_KEEPALIVE_MS=600000
      - PERSISTENCE=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"
      - "./localstack:/etc/localstack/init/ready.d"

volumes:
  localstack-data:
