service: lambda-demo-python

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-northeast-1
  environment: ${file(conf/${self:provider.stage}.yml)}

plugins:
  # - serverless-offline
  - serverless-localstack
  - serverless-python-requirements

custom:
  localstack:
    stages:
      - dev
    host: http://localstack
    edgePort: 4566
    apiGateway:
      restApiId: kpzmbrgvjm

functions:
  hello:
    handler: worker.Sample.hello
    events:
      - http:
          path: hello
          method: get

  users:
    handler: worker.User.get_users
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: users
          method: get
          cors: true

  user:
    handler: worker.User.get_user
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: users/{id}
          method: get
          cors: true

package:
  include:
    - /library
    - /repository
    - /worker
  exclude:
    - /node_module
    - /.serverless
    - /__pycache__
